# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guodong Ding's GitHub Pages
email: uberurey_ups@163.com
description: > # this means to ignore newlines until "baseurl:"
  Thank you for visiting my GitHub Pages, you can get some useful
  repositories here, :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dingguodong.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  DingGuodong

# Build settings
markdown: kramdown
